FROM python:3.9-slim

WORKDIR /usr/src

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copy the Flask app files
COPY admin ./admin
COPY common ./common
COPY lamda_consumer ./lambda_consumer

# Install the Python dependencies
RUN pip install --no-cache-dir -r admin/requirements.txt

CMD ["python", "lambda_consumer/main.py"]