FROM python:3.9-slim

WORKDIR /usr/src

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copy the Flask app files
COPY redirector ./redirector
COPY common ./common

# Install the Python dependencies
RUN pip install --no-cache-dir -r redirector/requirements.txt
RUN pip install --no-cache-dir gunicorn

# Expose the port
EXPOSE 8080

# Start gunicorn and the Flask app
RUN chmod +x redirector/entrypoint.sh
ENTRYPOINT "redirector/entrypoint.sh"
#CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8080", "--access-logfile=-", "redirector.app:create_app()"]